### ISSUE TITLE
Consider C-style Enum support

### ISSUE THREAD

**Issue by theduke** [dtolnay/miniserde#12]
I have a crate that has > 10_000 types that map a huge API and needs JSON serialization.
The compile time with `serde` proper is pretty severe, and miniserde would be a great improvement.

While I wouldn't need any fancy json <-> Rust enum mapping, I would really need support for basic C-style enums represented as strings.
I could map them as regular strings, create `From`/`Into` impls and provide accessor methods that map the strings to respective enums, but that would create so much overhead and probably error-prone code that it is a no-go. (or write a custom (proc) macro on top, but that creates a few complications that imo are prohibitive).

Would support for simple string-enum mappings be something that could be considered?

**Comment by dtolnay** [comment]
Thanks @theduke, I would accept a PR implementing C-style enums in the derive macro if it comes with a measurement of compile time for your 10k types crate with miniserde vs serde showing the improvement in compile time.
