### ISSUE TITLE
Make ryu and itoa optional

### ISSUE THREAD

**Issue by cloudhead** [dtolnay/miniserde#19]
Would you consider a pull request that made `ryu` and `itoa` optional? This would make the top-level library optionally have zero dependencies, for a small hit on performance.

This library is otherwise perfect for my usecase!

**Comment by dtolnay** [comment]
I would need you to provide some more detail on why the number of dependencies is significant for your use case. Is there a difference between the same code being under one crate vs across 3 crates maintained by the same person?

**Comment by cloudhead** [comment]
I'll try to explain. For the purposes of keeping my code easy to audit and work with, I'm looking for two things in the crates I depend on:

1) Small, clean codebase: less code to audit and faster builds
2) Small dependency footprint: less moving parts and potential security holes

The reason (2) is relevant for me is that even though these crates are maintained by you at the moment, they may not always be, and this is something that isn't necessarily apparent to someone using my library. Hence, it's an extra thing to keep track of, for little gain in my case. If the code was bundled in the same crate, it would satisfy (2), but of course would not reduce the code size.

Since json serialization is a very small part of the project I'm working on, and performance is not a factor, my dependency budget is *1*.

I understand that this is probably a weird requirement, I don't know how your crate is usually used vs. `serde`, so if this doesn't make sense for `miniserde`, I'm totally happy to fork it for my own use-case!

**Comment by dtolnay** [comment]
Thanks, that makes a lot of sense. I think I'll keep this as is for this crate, but a fork would be appropriate.

**Comment by cloudhead** [comment]
No worries, thanks for the great work you've been putting out!
