### ISSUE TITLE
guarantee stability of encoding

### ISSUE THREAD

**Issue by DavidBJaffe** [dtolnay/miniserde#20]
Feature request: could the README.md please assert that the encoded structure of the same data will not change over time as the crate or dependent crates are updated?  This would allow an application to write files, and be sure that those same files can be read later, under later versions of code.

Similarly, it would be great to guarantee that the storage is the same when used on different architectures, where, for example, the definition of usize might (hypothetically) vary.

My use case is actually simple enough that I'm inclined to directly write the encoding.  But these things I've asked for are things that seem to have general value.

**Comment by dtolnay** [comment]
This library doesn't make any of those guarantees.
