### ISSUE TITLE
Shall it contain adapters for Display and FromStr?

### ISSUE THREAD

**Issue by vi** [dtolnay/miniserde#3]
Like these:

```rust
macro_rules! miniserialize_for_display {
    ($t:ty) => {
        impl miniserde::Serialize for $t {
            fn begin(&self) -> miniserde::ser::Fragment {
                miniserde::ser::Fragment::Str(std::borrow::Cow::Owned(format!("{}",self)))
            }
        }
    };
}
macro_rules! minideserialize_for_fromstr {
    ($t:ty) => {
        impl miniserde::Deserialize for $t {
            fn begin(out: &mut Option<Self>) -> &mut dyn miniserde::de::Visitor {
                make_place!(Place);
                impl miniserde::de::Visitor for Place<$t> {
                    fn string(&mut self, s: &str) -> miniserde::Result<()> {
                        match std::str::FromStr::from_str(s) {
                            Ok(x) => {
                                self.out = Some(x);
                                Ok(())
                            },
                            Err(_) => Err(miniserde::Error),
                        }
                    }
                }
                Place::new(out)
            }
        }
    };
}
```

Combined with [strum](https://crates.io/crates/strum) it should provide easy miniserde for enums.

**Comment by dtolnay** [comment]
Thanks for the idea! I would prefer not to include these. Maybe there could be a separate crate that provides such helpers for implementing miniserde::Serialize and miniserde::Deserialize, like what we have for Serde with crates like [`serde_aux`](https://docs.rs/serde-aux/0.5.3/serde_aux/), [`serde_with`](https://docs.rs/serde_with/0.2.2/serde_with/), [`serde_plain`](https://docs.rs/serde_plain/0.3.0/serde_plain/). The macros you suggested are a lot like these two:

- [`serde_plain::derive_serialize_from_display!`](https://docs.rs/serde_plain/0.3.0/serde_plain/macro.derive_serialize_from_display.html)
- [`serde_plain::derive_deserialize_from_str!`](https://docs.rs/serde_plain/0.3.0/serde_plain/macro.derive_deserialize_from_str.html)

**Comment by vi** [comment]
Shall it be mini-crates for each adapter and helper or one general big "miniserde toolbox" enhancement crate?

**Comment by dtolnay** [comment]
If it were up to me, I would prefer one consolidated toolbox crate. But when adding any helpers that take a noticeable amount of time to compile or that pull in any additional dependencies, I would put those behind an off-by-default Cargo cfg. :smile_cat:

**Comment by dtolnay** [comment]
I posted a request for implementation in https://github.com/dtolnay/request-for-implementation/issues/11.
