### ISSUE TITLE
Support for more types

### ISSUE THREAD

**Issue by MendyBerger** [dtolnay/miniserde#46]
Would you be open to PRs adding support for more types? Here are some that would be useful in our project.

- Tuples with more than 2 values.
- Arrays.
- HashSet.
- std::time::Duration
- Tuple style structs
- Enums with values and generics.
- Unit structs.

For some of them I already have hacked together some code. Would you be open to such PRs?

**Comment by dtolnay** [comment]
Arrays would be okay. The others, I would not want in this crate.
