### ISSUE TITLE
Miniserde could not parse a JSON file that Serde can

### ISSUE THREAD

**Issue by Hyphrio** [dtolnay/miniserde#52]
I'm not certain where this issue is coming from as `serde` & `serde_json` could parse the file correctly while `miniserde` does not
Minimal reproduction: https://github.com/Hyphrio/miniserde_serde_parsing_differences

**Comment by dtolnay** [comment]
Miniserde does not implement a `rename_all` attribute. It should work if you use `rename` instead.

**Comment by Hyphrio** [comment]
Oh that might be it because weirdly enough miniserde doesn't reject it (tho probably just for compat with Serde)
I'll close this
